// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdfJeVqP7FisaqcwRlDLIpGv742Mtr8I',
    appId: '1:1097888533695:web:6cc7d33221bb84e101ca0a',
    messagingSenderId: '1097888533695',
    projectId: 'fir-clud-e5959',
    authDomain: 'fir-clud-e5959.firebaseapp.com',
    databaseURL: 'https://fir-clud-e5959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-clud-e5959.appspot.com',
    measurementId: 'G-5ZXJK6BBVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu9G7Y6DJiXk6Lp8Sr4R5NctC9_xsqIio',
    appId: '1:1097888533695:android:fffec2513888cef601ca0a',
    messagingSenderId: '1097888533695',
    projectId: 'fir-clud-e5959',
    databaseURL: 'https://fir-clud-e5959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-clud-e5959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpFerYuDBT_wNLaYdOZeDIr0Gbn8rjU0',
    appId: '1:1097888533695:ios:4a6fe3f33b4e35d401ca0a',
    messagingSenderId: '1097888533695',
    projectId: 'fir-clud-e5959',
    databaseURL: 'https://fir-clud-e5959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-clud-e5959.appspot.com',
    iosBundleId: 'com.example.pranerShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpFerYuDBT_wNLaYdOZeDIr0Gbn8rjU0',
    appId: '1:1097888533695:ios:4a6fe3f33b4e35d401ca0a',
    messagingSenderId: '1097888533695',
    projectId: 'fir-clud-e5959',
    databaseURL: 'https://fir-clud-e5959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-clud-e5959.appspot.com',
    iosBundleId: 'com.example.pranerShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpdfJeVqP7FisaqcwRlDLIpGv742Mtr8I',
    appId: '1:1097888533695:web:ae4182f0c34367c701ca0a',
    messagingSenderId: '1097888533695',
    projectId: 'fir-clud-e5959',
    authDomain: 'fir-clud-e5959.firebaseapp.com',
    databaseURL: 'https://fir-clud-e5959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-clud-e5959.appspot.com',
    measurementId: 'G-GV6CHT6W57',
  );
}
